/***************************************************************************//**
 * @note
 * Copyright (C) 2019-2022 MemryX Limited. All rights reserved.
 *
 ******************************************************************************/
#ifndef MEMX_TEST_H_
#define MEMX_TEST_H_

#ifdef __cplusplus
extern "C" {
#endif

/***************************************************************************//**
 * common include
 ******************************************************************************/
#include <stdio.h>

/***************************************************************************//**
 * error
 ******************************************************************************/
typedef enum _memx_test_result
{
  MEMX_TEST_PASS = 0,
  MEMX_TEST_FAIL = 1,

  MEMX_TEST_LIST_CREATE_MID_0_FAIL = 200,
  MEMX_TEST_LIST_PUSH_INIT_FAIL,
  MEMX_TEST_LIST_PUSH_NULL_0_FAIL,
  MEMX_TEST_LIST_PUSH_MID_0_FAIL,
  MEMX_TEST_LIST_PUSH_MID_1_FAIL,
  MEMX_TEST_LIST_POP_INIT_FAIL,
  MEMX_TEST_LIST_POP_NULL_0_FAIL,
  MEMX_TEST_LIST_POP_MIN_0_FAIL,
  MEMX_TEST_LIST_POP_MID_0_FAIL,
  MEMX_TEST_LIST_POP_MID_1_FAIL,
  MEMX_TEST_LIST_COUNT_INIT_FAIL,
  MEMX_TEST_LIST_COUNT_NULL_0_FAIL,
  MEMX_TEST_LIST_COUNT_MIN_0_FAIL,
  MEMX_TEST_LIST_COUNT_MID_0_FAIL,
  MEMX_TEST_LIST_COUNT_MID_1_FAIL,
  MEMX_TEST_LIST_FRONT_INIT_FAIL,
  MEMX_TEST_LIST_FRONT_NULL_0_FAIL,
  MEMX_TEST_LIST_FRONT_MIN_0_FAIL,
  MEMX_TEST_LIST_FRONT_MID_0_FAIL,
  MEMX_TEST_LIST_FRONT_MID_1_FAIL,
  MEMX_TEST_LIST_PEEK_INIT_FAIL,
  MEMX_TEST_LIST_PEEK_NULL_0_FAIL,
  MEMX_TEST_LIST_PEEK_NULL_1_FAIL,
  MEMX_TEST_LIST_PEEK_MIN_0_FAIL,
  MEMX_TEST_LIST_PEEK_MIN_1_FAIL,
  MEMX_TEST_LIST_PEEK_MID_0_FAIL,
  MEMX_TEST_LIST_PEEK_MAX_0_FAIL,
  MEMX_TEST_LIST_EXISTS_INIT_FAIL,
  MEMX_TEST_LIST_EXISTS_NULL_0_FAIL,
  MEMX_TEST_LIST_EXISTS_MIN_0_FAIL,
  MEMX_TEST_LIST_EXISTS_MID_0_FAIL,
  MEMX_TEST_LIST_EXISTS_MID_1_FAIL,
  MEMX_TEST_LIST_REMOVE_INIT_FAIL,
  MEMX_TEST_LIST_REMOVE_NULL_0_FAIL,
  MEMX_TEST_LIST_REMOVE_MIN_0_FAIL,
  MEMX_TEST_LIST_REMOVE_MID_0_FAIL,
  MEMX_TEST_LIST_REMOVE_MID_1_FAIL,
  MEMX_TEST_LIST_REMOVE_MID_2_FAIL,
  MEMX_TEST_LIST_REMOVE_MID_3_FAIL,

  MEMX_TEST_RINGBUFFER_CREATE_MIN_0_FAIL = 400,
  MEMX_TEST_RINGBUFFER_CREATE_MIN_1_FAIL,
  MEMX_TEST_RINGBUFFER_CREATE_MID_0_FAIL,
  MEMX_TEST_RINGBUFFER_CREATE_MID_1_FAIL,
  MEMX_TEST_RINGBUFFER_CREATE_MAX_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_INIT_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_NULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_NULL_1_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_MIN_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_MID_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_MAX_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_MAX_1_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_PART_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_PART_1_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_RING_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_RING_1_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_FULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_PUT_FULL_1_FAIL,
  MEMX_TEST_RINGBUFFER_GET_INIT_FAIL,
  MEMX_TEST_RINGBUFFER_GET_NULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_GET_NULL_1_FAIL,
  MEMX_TEST_RINGBUFFER_GET_MIN_0_FAIL,
  MEMX_TEST_RINGBUFFER_GET_MID_0_FAIL,
  MEMX_TEST_RINGBUFFER_GET_MAX_0_FAIL,
  MEMX_TEST_RINGBUFFER_GET_MAX_1_FAIL,
  MEMX_TEST_RINGBUFFER_GET_PART_0_FAIL,
  MEMX_TEST_RINGBUFFER_GET_PART_1_FAIL,
  MEMX_TEST_RINGBUFFER_GET_RING_0_FAIL,
  MEMX_TEST_RINGBUFFER_GET_RING_1_FAIL,
  MEMX_TEST_RINGBUFFER_GET_EMPTY_0_FAIL,
  MEMX_TEST_RINGBUFFER_GET_EMPTY_1_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_INIT_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_NULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_MIN_0_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_MID_0_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_MAX_0_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_MAX_1_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_PART_0_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_PART_1_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_RING_0_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_RING_1_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_EMPTY_0_FAIL,
  MEMX_TEST_RINGBUFFER_DROP_EMPTY_1_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_INIT_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_NULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_EMPTY_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_EMPTY_1_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_FULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_FULL_1_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_RING_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_USAGE_RING_1_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_INIT_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_NULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_EMPTY_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_EMPTY_1_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_FULL_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_FULL_1_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_RING_0_FAIL,
  MEMX_TEST_RINGBUFFER_PEAK_SPACE_RING_1_FAIL,

  MEMX_TEST_UART2AHB_CREATE_NULL_0_FAIL = 600,
  MEMX_TEST_UART2AHB_CREATE_MID_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_INIT_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_NULL_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_NULL_1_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_HDR_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_HDR_1_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_MIN_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_MIN_1_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_MID_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_MAX_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_WRITE_MAX_1_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_INIT_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_NULL_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_NULL_1_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_HDR_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_HDR_1_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_MIN_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_MIN_1_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_MID_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_MAX_0_FAIL,
  MEMX_TEST_UART2AHB_CONTROL_READ_MAX_1_FAIL,

  MEMX_TEST_CCIF_CREATE_MID_0_FAIL = 800,
  MEMX_TEST_CCIF_CONTROL_WRITE_INIT_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_NULL_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_NULL_1_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_HDR_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_MIN_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_MIN_1_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_MID_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_MAX_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_WRITE_MAX_1_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_INIT_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_NULL_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_NULL_1_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_HDR_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_MIN_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_MIN_1_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_MID_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_MAX_0_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_MAX_1_FAIL,
  MEMX_TEST_CCIF_CONTROL_READ_TIMEOUT_0_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_INIT_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_NULL_0_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_NULL_1_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_HDR_0_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_MIN_0_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_MIN_1_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_MID_0_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_MAX_0_FAIL,
  MEMX_TEST_CCIF_STREAM_WRITE_MAX_1_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_INIT_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_NULL_0_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_NULL_1_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_NULL_2_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_MIN_0_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_MIN_1_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_MID_0_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_MAX_0_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_MAX_1_FAIL,
  MEMX_TEST_CCIF_STREAM_READ_TIMEOUT_0_FAIL,

  MEMX_TEST_CASCADE_CREATE_NULL_0_FAIL,

  MEMX_TEST_GBF_ENCODE_FLOAT32_TO_GBF80_NULL_0_FAIL,
  MEMX_TEST_GBF_ENCODE_FLOAT32_TO_GBF80_NULL_1_FAIL,
  MEMX_TEST_GBF_ENCODE_FLOAT32_TO_GBF80_MIN_0_FAIL,
  MEMX_TEST_GBF_ENCODE_FLOAT32_TO_GBF80_MID_0_FAIL,
  MEMX_TEST_GBF_DECODE_GBF80_TO_FLOAT32_NULL_0_FAIL,
  MEMX_TEST_GBF_DECODE_GBF80_TO_FLOAT32_NULL_1_FAIL,
  MEMX_TEST_GBF_DECODE_GBF80_TO_FLOAT32_MIN_0_FAIL,
  MEMX_TEST_GBF_DECODE_GBF80_TO_FLOAT32_MID_0_FAIL,
  MEMX_TEST_GBF_DECODE_GBF80_TO_FLOAT32_MAX_0_FAIL,
  MEMX_TEST_GBF_DECODE_GBF80_TO_FLOAT32_MAX_1_FAIL,

} memx_test_result;

/***************************************************************************//**
 * helper
 ******************************************************************************/
#define memx_test_assert_null(_ptr_) ((_ptr_) == NULL)
#define memx_test_assert_not_null(_ptr_) ((_ptr_) != NULL)
#define memx_test_assert_equal(_val_a_, _val_b_) ((_val_a_) == (_val_b_))
#define memx_test_assert_not_equal(_val_a_, _val_b_) ((_val_a_) != (_val_b_))

/***************************************************************************//**
 * misc.
 ******************************************************************************/
#define MEMX_TESTCASE(_testname_) \
memx_test_result _testname_(void) \
{ \
  memx_test_result result = MEMX_TEST_PASS; \
  printf(" + %s ... ", (#_testname_));
#define MEMX_TESTCASE_END \
  printf("%d (%s)\n", (int)result, result ? "fail" : "pass"); \
  return result; \
}
#define memx_test_result_okay (result == MEMX_TEST_PASS)
#define memx_test_result_set(_result_) (result = (_result_))


#ifdef __cplusplus
}
#endif

#endif /* MEMX_TEST_H_ */

