#!/bin/sh

# Load debconf library
. /usr/share/debconf/confmodule


detect_bar256 () {

    # look for "size=256M" in lspci's output
    lspci -v -d 1fe9:0100 | grep "Memory\ at\ " | cut -d'=' -f2 | grep 256 >/dev/null
    if [ $? -eq 0 ]; then
        return 0
    else
        return 1
    fi

}


detect_bar16 () {

    # look for "size=16M" in lspci's output
    lspci -v -d 1fe9:0100 | grep "Memory\ at\ " | cut -d'=' -f2 | grep 16 >/dev/null
    if [ $? -eq 0 ]; then
        return 0
    else
        return 1
    fi

}


detect_valid_bar () {

    # if neither 256M nor 16M are available, return 1

    BUGGY=1
    detect_bar256
    if [ $? -eq 0 ]; then
        BUGGY=0
    fi
    detect_bar16
    if [ $? -eq 0 ]; then
        BUGGY=0
    fi

    return $BUGGY

}



db_get memx-drivers/requireAck
if [ "$RET" != "true" ]; then
    echo "User already declined the upgrade. Skipping!"
    exit 1
else

    if [ -x /usr/sbin/mxfw_pcie_update_flash ]; then

        VWHAT=$(virt-what)
        if [ -z "$VWHAT" ]; then
            # *IF* an MX3 is connected, check if it needs a firmware update
            lspci -n | grep -i "1fe9:0100" >/dev/null 2>&1
            if [ $? -eq 0 ]; then
    
                # make sure to unload the current driver!
                # otherwise our usage of /dev/mem will cause issues
                echo "Removing running module (if present)"
                rmmod memx_cascade_plus_pcie #ignore failures
    
                echo "Analyzing connected MX3s..."

                MACHINE=$(uname -m)
                # yes, single '=' is right because /bin/sh is dumb
                if [ $MACHINE = "arm64" ]; then
                    CPU_IS_ARM=1
                elif [ $MACHINE = "aarch64" ]; then
                    CPU_IS_ARM=1
                else
                    CPU_IS_ARM=0
                fi

                # abort checking if there's a buggy BAR
                detect_valid_bar
                if [ $? -ne 0 ]; then
                    if [ $CPU_IS_ARM -eq 1 ]; then
                        echo "\033[93mWARNING!\033[0m Skipped firmware check because the system does not yet have functioning PCIe BAR. Please run 'sudo mx_arm_setup' and manually update firmware (https://developer.memryx.com/tutorials/how_to/update_firmware.html)"
                    else
                        echo "\033[91mWARNING!\033[0m System does not appear to have properly functioning PCIe BARs for MX3"
                    fi
                fi

                /usr/sbin/mxfw_check_version -b >/dev/null 2>&1
                if [ $? -eq 0 ]; then
                    echo "Connected MX3 does not use flash boot, no upgrade needed."
                elif [ $? -eq 1 ]; then

                    # is this *actually* a 16M BAR MXMF card??
                    detect_bar16
                    if [ $? -eq 0 ]; then

                        echo "Flash booted MX3 found. Checking for firmware update..."
    
                        CURVER=$(/usr/sbin/mxfw_check_version -f)
                        /usr/bin/mxfw_read_fwver -f /lib/firmware/cascade_4chips_flash.bin | grep -i $CURVER >/dev/null 2>&1
                        if [ $? -eq 0 ]; then
                            echo "Latest firmware already installed."
                        else
                            echo "Update available! Now updating firmware on detected MX3 devices..."
                            /usr/sbin/mxfw_pcie_update_flash -f /lib/firmware/cascade_4chips_flash.bin
                            if [ $? -eq 0 ]; then
                                echo "Success! \033[96mBe sure to restart your computer\033[0m"
                            else
                                echo "\033[91mFirmware update failed!\033[0m"
                            fi
                        fi

                    fi
                fi
            fi
        else
            echo "Running in $VWHAT , skipping firmware checks"
        fi
    
        echo "Building MX3 DKMS module..."
        DKMS_NAME=memx-drivers
        DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
        DKMS_VERSION=$(ls /usr/src | grep memx-drivers | grep -oP "(?<=drivers-).*")
        
        postinst_found=0
        build_status=0
        
        case "$1" in
            configure)
                for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
                    if [ -f $DKMS_POSTINST ]; then
                        $DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
                        build_status=$?
                        postinst_found=1
                        break
                    fi
                done
                if [ "$postinst_found" -eq 0 ]; then
                    echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
                    echo "built with legacy DKMS support."
                    echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
                    echo "support or upgrade DKMS to a more current version."
                    exit 1
                fi
            ;;
        esac

        if [ $build_status -ne 0 ]; then
            echo "\033[91mERROR!\033[0m DKMS module build seems to have failed!"
            exit 1
        else 
            echo "\033[93mNOTE!\033[0m A system reboot is required!"
        fi
    
    else
        echo "/usr/sbin/mxfw_pcie_update_flash is not available or not executable. \033[91mThe installer script shouldn't reach here\033[0m"
        exit 1
    fi
fi
